show databases;
CREATE DATABASE JOINT;
use joint;
#CREATE TWO TABLE IN JOINT DATABASE 1.EMPLOYEE_DETAILS 2.EMPLOYEE_DEPTT
 CREATE TABLE JOINT.Employee_Details(
EMP_ID INT,
EMP_NAME VARCHAR(20),
GENDER VARCHAR (8),
AGE INT,
SALARY INT);
DESCRIBE JOINT.EMPLOYEE_DETAILS;
insert into joint.EMPLOYEE_DETAILS values (101, "AJAY KUMAR", "MALE", 32, 100000),
(102, "ASHUTOSH MISHRA", "MALE", 28, 90000) ,
(103, "SWATI GAUTAM", "FEMALE", 29, 80000),
(104, "JAYA JOHSI",  "FEMALE", 27, 70000),
(105, "SIKHA", "FEMALE", 31, 60000),
(106, "SHILPI JAIN", "FEMALE", 35, 52000),
(107, "RAHUL KUAMR", "MALE", 35, 50000),
(108, "SONU AGGARWAL", "MALE", 40, 45000);
select * FROM JOINT.EMPLOYEE_DETAILS;
USE JOINT;
CREATE table JOINT.EMPLOYEE_DEPTT(
DEPTT_ID INT,
EMP_ID INT,
DEPARTMENT VARCHAR (20),
CITY VARCHAR(20),
PINCODE INT);
INSERT INTO EMPLOYEE_DEPTT VALUES (521, 102, "ENGINEER", "REWA", 97852),
(522, 101, "CEO", "DELHI", 11006 ),
(526, 102, "DATA ANALYST", "BANGOLRE", 110053),
(525, 103, "ENGINEER", "DELHI", 100636),
(527, 114, "MARKETING", "JABALPUR", 663352),
(528, 115, "SALES", "ALLAHBAAD", 852638),
(529, 116, "TEACHEING", "HAPUR", 852639),
(530, 117, "HR", "NOIDA", 6633552);
# 1. INNER JOIN
SELECT * FROM JOINT.EMPLOYEE_DETAILS INNER JOIN JOINT.EMPLOYEE_DEPTT
 ON EMPLOYEE_DETAILS.EMP_ID = EMPLOYEE_DEPTT.EMP_ID;
 # 2. RIGHT JOIN/RIGHT OUTER JOIN
 SELECT * FROM EMPLOYEE_DETAILS RIGHT JOIN EMPLOYEE_DEPTT ON EMPLOYEE_DETAILS.EMP_ID = EMPLOYEE_DEPTT.EMP_ID;
 # 3. LEFT JOINT/ LEFT OUTER JOIN
 SELECT * FROM EMPLOYEE_DETAILS LEFT JOIN EMPLOYEE_DEPTT ON EMPLOYEE_DETAILS.EMP_ID = EMPLOYEE_DEPTT.EMP_ID;
 # 4. FULL JOIN/ FULL OUTER JOIN
 SELECT * FROM EMPLOYEE_DETAILS FULL JOIN EMPLOYEE_DEPTT ON EMPLOYEE_DEPTT.EMP_ID = EMPLOYEE_DEPTT.EMP_ID;
 # 5. NATURAL JOIN (a.NATURAL RIGHT JOIN b. NATURAL LEFT JOIN)
 # a. NATURAL RIGHT JOIN
 SELECT * FROM EMPLOYEE_DETAILS natural right join employee_deptt;
 # b. NAUTAL LEFT JOIN
 SELECT * FROM EMPLOYEE_DETAILS natural left join employee_deptt;
 # 6. CROSS JOIN
 SELECT * FROM EMPLOYEE_DETAILS CROSS JOIN EMPLOYEE_DEPTT;
 # 7. SELF JOIN
 SELECT EMP_ID, SALARY FROM EMPLOYEE_DETAILS WHERE SALARY < 100000;
 #THANK YOU.